### ISSUE TITLE
Can I use Midbar to encrypt variables

### ISSUE THREAD

**Issue by Cancro29** [Northstrix/Midbar#1]
I want to encrypt some strings and uint8_t on my project. Midbar seems to be perfect for this. Is there a simpler Arduino code that demonstrates encryption and decryption process?

**Comment by Northstrix** [comment]
Yes, there is. You can find the code that enables you to encrypt your strings, or the uint8_t arrays (if you adjust it a bit and handle the padding) in some of the "extra" folders, like:

https://github.com/Northstrix/Midbar/tree/main/Raspberry_Pi_Pico_Version/V1.0/extra/TDES_AES_Blowfish_Serpent_CBC
https://github.com/Northstrix/Midbar/tree/main/Teensy%204.1%20Version/V1.0/extra/TDES_AES_Blowfish_Serpent_CBC
https://github.com/Northstrix/Midbar/tree/main/ESP32_Version/V2.5/extra/TDES_AES_Blowfish_Serpent_CBC
https://github.com/Northstrix/Midbar/tree/main/RTL8720DN%20Version/V1.0/extra

Alternatively, you can use this code:
https://github.com/Northstrix/AES_in_CBC_mode_for_microcontrollers
https://github.com/Northstrix/Serpent_in_CBC_mode_for_microcontrollers
